# tracker/report.py

import os

def build_markdown_report(records):
    """
    Membuat string laporan dalam format Markdown dari daftar rekap.
    """
    # Header
    content = ["# Rekap Nilai Mahasiswa", ""]
    
    # Header Tabel (dengan perataan kanan untuk angka)
    content.append("| NIM | Nama | Hadir (%) | Nilai Akhir | Predikat |")
    content.append("|---|---|---:|---:|---|")
    
    # Isi Tabel
    for r in records:
        line = (
            f"| {r['nim']} | {r['nama']} | {r['hadir']:.1f} | "
            f"{r['nilai_akhir']:.2f} | {r['predikat']} |"
        )
        content.append(line)
        
    # Footer
    content.append("\nGenerated by student_performance_tracker")
    
    return "\n".join(content)


def save_text(path, content):
    """
    Menyimpan konten string ke file di path yang ditentukan.
    Akan membuat direktori 'out/' jika belum ada.
    """
    try:
        # Memastikan direktori (cth: 'out/') ada
        dirname = os.path.dirname(path)
        if dirname and not os.path.exists(dirname):
            os.makedirs(dirname)
            
        # Menulis file
        with open(path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"Laporan berhasil disimpan ke: {path}")
        
    except IOError as e:
        print(f"Error saat menyimpan file: {e}")